### ISSUE TITLE
MediaWiki SSL update

### ISSUE THREAD

**Issue by djengineerllc** [natxo/nagios_plugins#1]
Just wanted to let you know that MediaWiki has updated to SSL for their download page.

I ended up changing:
my $mw_dl_url = "http://www.mediawiki.org/wiki/Download";
to:
my $mw_dl_url = "https://www.mediawiki.org/wiki/Download";

I'm using Debian and also had to download a perl library to allow the get to the HTTPS site:
apt-get install libcrypt-ssleay-perl

Hopefully this can help other out who are using this as well.

**Comment by natxo** [comment]
Thanks for the report :-)

I will update the plugin info. I had not notified this because I already had the Crypt::SSLeay module and WWW::Mechanize was correctly following the 301 redirect.

**Comment by djengineerllc** [comment]
Oh ok, yeah, I just had a Turnkey Core 13 (Debian) server setup with nagios installed on it.  It is a pretty bare server. :)
